name: AWS Environment Variables
author: hitsuzen-002
description: AWS Environment Variables

outputs:
  AWS_STG_ACCESS_KEY_ID:
    description: 'AWS Staging Access Key ID'
    value: ${{ steps.set_env.outputs.AWS_STG_ACCESS_KEY_ID }}
  AWS_STG_INSTANCE_ID:
    description: 'AWS Staging Instance ID'
    value: ${{ steps.set_env.outputs.AWS_STG_INSTANCE_ID }}
  AWS_STG_REGION:
    description: 'AWS Staging Region'
    value: ${{ steps.set_env.outputs.AWS_STG_REGION }}

runs:
  using: "composite"
  steps:
    - name: Set AWS Staging Environment Variables
      id: set_env
      env:
        AWS_STG_INSTANCE_ID : i-07ca443c8a566e554
        AWS_STG_REGION : us-east-1
        AWS_STG_ACCESS_KEY_ID : AKIAU72LF6A66T7M2HEJ
      shell: bash
      run: |
        echo "AWS_STG_INSTANCE_ID=${AWS_STG_INSTANCE_ID}" >> $GITHUB_OUTPUT
        echo "AWS_STG_REGION=${AWS_STG_REGION}" >> $GITHUB_OUTPUT
        echo "AWS_STG_ACCESS_KEY_ID=${AWS_STG_ACCESS_KEY_ID}" >> $GITHUB_OUTPUT
