name: Production Deployment

on:
  workflow_call:
    inputs:
      app-path:
        description: 'Path to the application on the target server'
        required: false
        type: string
        default: '/var/www/vhosts/multisender.easy-go.me'
      artifact-url:
        description: 'URL of the artifact to download'
        required: false
        type: string
        
jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        id: set-env-vars
        run: |
          echo "AWS_REGION=${{ secrets.AWS_PROD_REGION }}" >> $GITHUB_OUTPUT
          echo "AWS_INSTANCE_ID=${{ secrets.AWS_PROD_INSTANCE_ID }}" >> $GITHUB_OUTPUT
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_PROD_ACCESS_KEY_ID }}" >> $GITHUB_OUTPUT
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}" >> $GITHUB_OUTPUT
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ steps.set-env-vars.outputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ steps.set-env-vars.outputs.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ steps.set-env-vars.outputs.AWS_REGION }}

      - name: Deploy using SSM
        run: |
          # SSMを使用してデプロイスクリプトを実行
          aws ssm send-command \
            --instance-ids ${{ steps.set-env-vars.outputs.AWS_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{
              "commands": [
                "sudo su deploy",
                "cd ${{ inputs.app-path }}",
                "rm -rf ./* || true",
                "# URLからアーティファクトをダウンロード",
                "curl -L -H \"Authorization: token ${{ secrets.GITHUB_TOKEN }}\" ${{ inputs.artifact-url }} --output artifact.zip",
                "# 展開",
                "unzip -q artifact.zip",
                "rm artifact.zip",
                "# アプリケーション再起動",
                "pm2 restart npm --name multisender-pm2 -- run prod",
                "pm2 ls"
              ]
            }' \
            --output text 