name: Production Deployment

on:
  workflow_call:
    inputs:
      app-path:
        description: 'Path to the application on the target server'
        required: false
        type: string
        default: '/var/www/vhosts/multisender.easy-go.me'
      artifact-name:
        description: 'Name of the artifact to download'
        required: false
        type: string
        default: 'build-output'

env:
  AWS_REGION: ${{ secrets.AWS_PROD_REGION }}
  AWS_INSTANCE_ID: ${{ secrets.AWS_PROD_INSTANCE_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
  AWS_ROLE_ARN: ${{ secrets.AWS_PROD_ROLE_ARN }}

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.AWS_INSTANCE_ID }}
          path: ./build

      - name: Create deployment package
        id: create-package
        run: |
          cd build
          # デプロイパッケージをbase64エンコード
          CONTENT=$(tar -cz * | base64 -w0)
          echo "package_content=${CONTENT}" >> $GITHUB_OUTPUT

      - name: Deploy using SSM
        run: |
          # SSMを使用してデプロイスクリプトを実行
          aws ssm send-command \
            --instance-ids ${{ env.AWS_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters commands=["cd ${{ inputs.app-path }}", \
                                  "rm -rf ./* || true", \
                                  "echo \"${{ steps.create-package.outputs.package_content }}\" | base64 -d | tar -xz", \
                                  "sudo su deploy", \
                                  "pm2 restart npm --name multisender-pm2 -- run prod", \
                                  "pm2 ls"] \
            --output text 