name: Build Only

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Select Environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - staging
          - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip test"

  eslint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip eslint"
      
  build:
    uses: ./.github/workflows/_build.yml
    with:
      node-version: '22'
      artifact-name: 'build-output'
      artifact-path: 'build'