name: Build Only

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Select Environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - staging
          - production

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print selected environment
        run: |
          echo "Selected environment: ${{ github.event.inputs.environment }}"
  aaaa:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Print selected environment
        run: |
          echo "Selected environment: ${{ github.event.inputs.environment }}"
