name: Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - "staging"
          - "production"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print selected environment
        run: echo "Selected environment: ${{ github.event.inputs.environment }}"
