name: Build Only

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Select Environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - staging
          - production

jobs:
      
  build:
    uses: ./.github/workflows/_build.yml
    with:
      node-version: '22'
      artifact-name: 'build-output'
      artifact-path: 'build'
      env-file: ${{ inputs.logLevel == 'staging' && 'stg' || 'production' }}