name: Build Only

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Select Environment'
        required: true
        default: 'warning'
        type: choice
        options:
          - staging
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        uses: ./.github/actions/build/
        with:
          node-version: '18'
          artifact-name: 'build-output'
          artifact-path: 'build'