name: Build & Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:

  vars:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'
    outputs:
      environment: ${{ github.event.inputs.environment }}
      instance-id: ${{ secrets.AWS_PROD_INSTANCE_ID }}
      region: ${{ secrets.AWS_PROD_REGION }}
      aws-role: ${{ secrets.AWS_PROD_ROLE_ARN }}
      artifact-name: 'build-output'
      aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
      app-path: ${{ secrets.AWS_PROD_APP_PATH }}
    steps:
      - run: echo "Set production environment variables"
        
  build:
    needs: vars
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        uses: ./.github/actions/build/
        with:
          node-version: '18'
          artifact-name: 'build-output'
          artifact-path: 'build'

  deploy:
    needs:
      - vars
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        if: needs.vars.outputs.environment == 'production'
        uses: ./.github/actions/deploy/prod/
        with:
          instance-id: ${{ needs.vars.outputs.instance-id }}
          region: ${{ needs.vars.outputs.region }}
          aws-access-key-id: ${{ needs.vars.outputs.aws-access-key-id }}
          aws-secret-access-key: ${{ needs.vars.outputs.aws-secret-access-key }}
          app-path: ${{ needs.vars.outputs.app-path }}
          artifact-name: ${{ needs.vars.outputs.artifact-name }}