name: Build
on:
  workflow_dispatch:
    inputs:
        environment:
            description: 'Environment to deploy to'
            required: true
            default: 'staging'
            options:
              - 'staging'
              - 'production'

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2