name: Build & Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      
jobs:

  vars:
    name: Vars Job
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'
    outputs:
      environment: ${{ github.event.inputs.environment }}
      artifact-name: 'build-output'
      node-version: '22'
      app-path: '/var/www/vhosts/multisender.easy-go.me'
    steps:
      - run: echo "Set production environment variables"
        
  build:
    name: Build Job
    needs: vars
    uses: ./.github/workflows/_build.yml
    with:
      node-version: ${{ needs.vars.outputs.node-version }}
      artifact-name: ${{ needs.vars.outputs.artifact-name }}
      artifact-path: 'build'

  deploy:
    name: Deploy Job
    needs:
      - vars
      - build
    if: needs.vars.outputs.environment == 'production'
    uses: ./.github/workflows/_prod_deploy.yml
    with:
      app-path: ${{ needs.vars.outputs.app-path }}
      artifact-name: ${{ needs.vars.outputs.artifact-name }}
    secrets: inherit