name: Test Deploy
on:
  push:
  workflow_dispatch:

jobs:

  vars:
    name: Vars Job
    runs-on: ubuntu-latest
    outputs:
      environment: 'production'
      artifact-name: 'build-output'
      app-path: '/var/www/vhosts/multisender.easy-go.me_test_deploy'
      node-version: '22'
    steps:
      - run: echo "Set production environment variables"


  dummy_build:
    needs: vars
    name: Build( Dummy )
    runs-on: ubuntu-latest
    outputs:
      build-directory: ${{ steps.build-step.outputs.build-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        id: build-step
        run: |
          mkdir build -p
          echo "tetetetete" >> build/test.txt
          echo "build-directory=$(pwd)/build" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.vars.outputs.artifact-name }}
          path: 'build'

  deploy:
    name: Deploy Job ( Prod )
    needs:
      - vars
      - dummy_build
    if: needs.vars.outputs.environment == 'production'
    uses: ./.github/workflows/_prod_deploy.yml
    with:
      app-path: ${{ needs.vars.outputs.app-path }}
      artifact-name: ${{ needs.vars.outputs.artifact-name }}
    secrets: inherit