name: Run Vitest

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Clean Install (fix for Rollup Linux module)
        run: |
          rm -f package-lock.json
          rm -rf node_modules

      - name: Install
        run: npm i

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest
        run: npm run test